### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by dragosv** [maciejhirsz/ramhorns#4]
Just wondering if the License is intended, as GPL is very restrictive for commercial use, requiring one to release the code. Can you change to MIT or similar?

**Comment by maciejhirsz** [comment]
GPL is very much intended. I will provide an option for a different license on request, but for now GPL it is.

**Comment by mmstick** [comment]
Perhaps the Mozilla Public License 2.0 would be a better fit? It provides the same benefits as the GPL, requiring that any changes made to your crate are open sourced, but would not force any software that links to it to change their license to match.

Currently, this crate requires the dependant to also be GPL, so any open source project with a permissive license is forbidden to use it. The LGPL wouldn't be any better, because Rust statically-links by default. Wrapping the crate in a microservice with RPC can be used to circumvent the GPL, for any that really want to use it, though chances are that askama, or something else, will be used instead.

**Comment by maciejhirsz** [comment]
I'm afraid that wouldn't address [my worries](http://maciej.codes/2019-03-09-why-gpl.html). I'd be fine with a double license, with the second license being permissive but only available to projects that do not do user tracking or violate privacy (regardless wether they are commercial or not).

**Comment by tomberek** [comment]
Would GPLv2 be acceptable?
